version: "3.8"
services:
  postgres-db:
    container_name: postgres
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgresql_data:
    driver: local
